name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BACKEND_DIR: backend
  FRONTEND_DIR: frontend
  PYTHON_VERSION: "3.10"

jobs:
  install-and-test:
    name: Install & Test Backend + Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Backend Setup
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Backend dependencies
        working-directory: ${{ env.BACKEND_DIR }}
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Check Backend for syntax errors
        working-directory: ${{ env.BACKEND_DIR }}
        run: python -m py_compile $(find . -name "*.py")

      - name: Run Backend tests
        working-directory: ${{ env.BACKEND_DIR }}
        run: |
          source venv/bin/activate
          PYTHONPATH=./ pytest

      # Frontend Setup
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend dependencies
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm install

      - name: Build Frontend
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm run build

      - name: Run Frontend tests
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm test

